// template/template_vuejs/src/pages/Page-boxed-layout-with-mixed-menu.vue
<template>
	<div>
		<!-- begin breadcrumb -->
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
			<li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
			<li class="breadcrumb-item active">Boxed Layout with Mixed Menu</li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">Boxed Layout with Mixed Menu <small>header small text goes here...</small></h1>
		<!-- end page-header -->
		<!-- begin panel -->
		<panel title="Panel Title here">
			Panel Content Here
		</panel>
		<!-- end panel -->
	</div>
</template>

<script>
import PageOptions from '../config/PageOptions.vue'

export default {
	created() {
		document.body.className = document.body.className + ' boxed-layout';
		PageOptions.pageWithTopMenu = true;
	},
	beforeRouteLeave (to, from, next) {
		document.body.className = document.body.className.replace('boxed-layout');
		PageOptions.pageWithTopMenu = false;
		next();
	}
}
</script>

// template/template_react/src/pages/option/page-boxed-layout-with-mixed-menu.js
import React from 'react';
import { Link } from 'react-router-dom';
import { Panel, PanelHeader, PanelBody } from './../../components/panel/panel.jsx';
import { PageSettings } from './../../config/page-settings.js';

class PageBoxedLayoutWithMixedMenu extends React.Component {
	static contextType = PageSettings;

	componentDidMount() {
		this.context.handleSetPageBoxedLayout(true);
		this.context.handleSetPageTopMenu(true);
	}

	componentWillUnmount() {
		this.context.handleSetPageBoxedLayout(false);
		this.context.handleSetPageTopMenu(false);
	}
  
	render() {
		return (
			<div>
				<ol className="breadcrumb float-xl-right">
					<li className="breadcrumb-item"><Link to="/page-option/boxed-layout-with-mixed-menu">Home</Link></li>
					<li className="breadcrumb-item"><Link to="/page-option/boxed-layout-with-mixed-menu">Page Options</Link></li>
					<li className="breadcrumb-item active">Boxed Layout with Mixed Menu</li>
				</ol>
				<h1 className="page-header">Boxed Layout with Mixed Menu <small>header small text goes here...</small></h1>
				<Panel>
					<PanelHeader>Panel Title here</PanelHeader>
					<PanelBody>
						Panel Content Here
					</PanelBody>
				</Panel>
			</div>
		)
	}
}

export default PageBoxedLayoutWithMixedMenu;
