// template/template_react_startup/src/components/footer/footer.jsx
import React from 'react';

class Footer extends React.Component {
	constructor(props) {
		super(props);
		
		var date = new Date();
		this.state = {
			year: date.getFullYear()
		}
	}
	render() {
		return (
			<div id="footer" className="footer">
				&copy; { this.state.year } Color Admin Responsive Admin Template - Sean Ngu All Rights Reserved
			</div>
		)
	}
}

export default Footer;

// template/template_vuejs/src/components/footer/Footer.vue
<template>
	<!-- begin #footer -->
	<div id="footer" class="footer">
		&copy; 2020 Color Admin Responsive Admin Template - Sean Ngu All Rights Reserved
	</div>
	<!-- end #footer -->
</template>

<script>
import PageOptions from '../../config/PageOptions.vue'

export default {
  name: 'Footer',
  data() {
		return {
			pageOptions: PageOptions
		}
  }
}
</script>
