// template/template_react/src/components/sidebar-right/sidebar-right.jsx
import React from 'react';
import { Collapse, CardHeader, CardBody, Card } from 'reactstrap';
import { PageSettings } from './../../config/page-settings.js';

class SidebarRight extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			collapse: [
				{	id: 1, collapse: true },
				{	id: 2, collapse: false },
				{	id: 3, collapse: false },
				{	id: 4, collapse: false },
				{	id: 5, collapse: false },
				{	id: 6, collapse: false },
				{	id: 7, collapse: false },
			]
		};
		this.toggleCollapse = this.toggleCollapse.bind(this);
	}

	toggleCollapse(index) {
		var newArray = [];
		for (let collapseObj of this.state.collapse) {
			if (collapseObj.id === index) {
				collapseObj.collapse = !collapseObj.collapse;
			} else {
				collapseObj.collapse = false;
			}
			newArray.push(collapseObj);
		}

		this.setState({
			collapse: newArray
		});
	}
  
	render() {
		return (
			<PageSettings.Consumer>
				{({pageTwoSidebar}) => (
					<React.Fragment>
						{pageTwoSidebar && (
							<React.Fragment>
								<div id="sidebar-right" className="sidebar sidebar-right">
									<div className="overflow-scroll height-full">
										<ul className="nav">
											<li className="nav-widget p-0">
												<p className="text-white m-0 p-15">Accordion</p>
												<div id="accordion" className="accordion">
													{
														this.state.collapse.map((value, i) => (
														<Card className="bg-dark text-white border-0" key={i}>
															<CardHeader className={'card-header bg-dark-darker text-white pointer-cursor border-0 ' + (!value.collapse ? 'collapsed ' : '')} onClick={() => this.toggleCollapse(value.id)}>
																<i className="fa fa-circle text-teal f-s-8 mr-2"></i> Accordion Item #{value.id}
															</CardHeader>
															<Collapse isOpen={value.collapse}>
																<CardBody className="p-15">
																	Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus.
																</CardBody>
															</Collapse>
														</Card>
														))
													}
												</div>
											</li>
										</ul>
									</div>
								</div>
								<div className="sidebar-bg sidebar-right"></div>
							</React.Fragment>
						)}
					</React.Fragment>
				)}
			</PageSettings.Consumer>
		)
	}
}


export default SidebarRight;

// template/template_vuejs/src/components/sidebar-right/SidebarRight.vue
<template>
	<div>
		<!-- begin #sidebar-right -->
		<div id="sidebar-right" class="sidebar sidebar-right">
			<!-- begin sidebar scrollbar -->
			<vue-custom-scrollbar class="height-full">
				<!-- begin sidebar user -->
				<ul class="nav">
					<li class="nav-widget p-0">
						<p class="text-white p-15 m-0">Accordion</p>
						<!-- begin #accordion -->
						<div id="accordion" class="accordion">
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion1>
									Accordion #1
									<i class="fa fa-plus-circle text-blue ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion1" visible accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion2>
									Accordion #2
									<i class="fa fa-plus-circle text-purple ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion2" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion3>
									Accordion #3
									<i class="fa fa-plus-circle text-teal ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion3" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion4>
									Accordion #4
									<i class="fa fa-plus-circle text-info ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion4" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion5>
									Accordion #5
									<i class="fa fa-plus-circle text-warning ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion5" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion6>
									Accordion #6
									<i class="fa fa-plus-circle text-danger ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion6" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
							<!-- begin b-card -->
							<b-card class="bg-dark text-white" no-body>
								<b-card-header header-tag="header" class="card-header bg-dark-darker b-0 text-white pointer-cursor d-flex align-items-center" v-b-toggle.accordion7>
									Accordion #7
									<i class="fa fa-plus-circle text-muted ml-auto mr-0"></i>
								</b-card-header>
								<b-collapse id="accordion7" accordion="my-accordion">
									<b-card-body>
										Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
									</b-card-body>
								</b-collapse>
							</b-card>
							<!-- end b-card -->
						</div>
						<!-- end #accordion -->
					</li>
				</ul>
				<!-- end sidebar user -->
			</vue-custom-scrollbar>
			<!-- end sidebar scrollbar -->
		</div>
		<div class="sidebar-bg sidebar-right"></div>
		<!-- end #sidebar-right -->
	</div>
</template>

<script>
import PageOptions from '../../config/PageOptions.vue'

export default {
  name: 'SidebarRight',
  data() {
		return {
			pageOptions: PageOptions
		}
  }
}
</script>
