// template/template_react/src/pages/email/email-detail.js
import React from 'react';
import { Link } from 'react-router-dom';
import { PageSettings } from './../../config/page-settings.js';
import PerfectScrollbar from 'react-perfect-scrollbar';

class EmailDetail extends React.Component {
	static contextType = PageSettings;

	constructor(props) {
		super(props);

		this.toggle = this.toggle.bind(this);
		this.toggleMobileEmailNav = this.toggleMobileEmailNav.bind(this);
		this.state = {
			dropdownOpen: false,
			isMobileEmailNavOn: false
		};
	}

	componentDidMount() {
		this.context.handleSetPageContentFullHeight(true);
		this.context.handleSetPageContentFullWidth(true);
	}

	componentWillUnmount() {
		this.context.handleSetPageContentFullHeight(false);
		this.context.handleSetPageContentFullWidth(false);
	}

	toggle() {
		this.setState(prevState => ({
			dropdownOpen: !prevState.dropdownOpen
		}));
	}
	
	toggleMobileEmailNav() {
		this.setState(state => ({
      isMobileEmailNavOn: !state.isMobileEmailNavOn
    }));
	}
  
	render() {
		return (
			<div className="vertical-box with-grid inbox bg-light">
				<div className="vertical-box-column width-200 hidden-xs">
					<div className="vertical-box">
						<div className="wrapper text-center">
							<div className="d-flex align-items-center justify-content-center">
								<button onClick={this.toggleMobileEmailNav} className="btn btn-inverse btn-sm mr-auto d-block d-lg-none">
									<i className="fa fa-cog"></i>
								</button>
								<Link to="/email/compose" className="btn btn-inverse p-l-40 p-r-40 btn-sm">
									Compose
								</Link>
							</div>
						</div>
						<div className={"vertical-box-row collapse d-lg-table-row " + (this.state.isMobileEmailNavOn ? 'show' : '') }>
							<div className="vertical-box-cell">
								<div className="vertical-box-inner-cell">
									<PerfectScrollbar className="height-full" options={{suppressScrollX: true}}>
										<div className="wrapper p-0">
											<div className="nav-title"><b>FOLDERS</b></div>
											<ul className="nav nav-inbox">
												<li><Link to="/email/inbox"><i className="fa fa-inbox fa-fw m-r-5"></i> Inbox <span className="badge pull-right">52</span></Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-flag fa-fw m-r-5"></i> Important</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-envelope fa-fw m-r-5"></i> Sent</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-pencil-alt fa-fw m-r-5"></i> Drafts</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-trash fa-fw m-r-5"></i> Trash</Link></li>
											</ul>
											<div className="nav-title"><b>LABEL</b></div>
											<ul className="nav nav-inbox">
												<li><Link to="/email/inbox"><i className="fa fa-fw f-s-10 m-r-5 fa-circle text-inverse"></i> Admin</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-fw f-s-10 m-r-5 fa-circle text-primary"></i> Designer & Employer</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-fw f-s-10 m-r-5 fa-circle text-success"></i> Staff</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-fw f-s-10 m-r-5 fa-circle text-warning"></i> Sponsorer</Link></li>
												<li><Link to="/email/inbox"><i className="fa fa-fw f-s-10 m-r-5 fa-circle text-danger"></i> Client</Link></li>
											</ul>
										</div>
									</PerfectScrollbar>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div className="vertical-box-column">
					<div className="vertical-box">
						<div className="wrapper clearfix">
							<div className="pull-left">
								<div className="btn-group m-r-5">
									<button className="btn btn-white btn-sm"><i className="fa fa-reply m-r-3 m-r-xs-0"></i> <span className="hidden-xs">Reply</span></button>
								</div>
								<div className="btn-group m-r-5">
									<button className="btn btn-white btn-sm"><i className="fa fa-trash m-r-3 m-r-xs-0"></i> <span className="hidden-xs">Delete</span></button>
									<button className="btn btn-white btn-sm"><i className="fa fa-archive m-r-3 m-r-xs-0"></i> <span className="hidden-xs">Archive</span></button>
								</div>
							</div>
							<div className="pull-right">
								<div className="btn-group">
									<Link to="/email/inbox" className="btn btn-white btn-sm disabled"><i className="fa fa-arrow-up"></i></Link>
									<Link to="/email/inbox" className="btn btn-white btn-sm"><i className="fa fa-arrow-down"></i></Link>
								</div>
								<div className="btn-group m-l-5">
									<Link to="/email/inbox" className="btn btn-white btn-sm"><i className="fa fa-times"></i></Link>
								</div>
							</div>
						</div>
						<div className="vertical-box-row bg-white">
							<div className="vertical-box-cell">
								<div className="vertical-box-inner-cell">
									<PerfectScrollbar className="height-full" options={{suppressScrollX: true}}>
										<div className="wrapper">
											<h3 className="m-t-0 m-b-15 f-w-500">Bootstrap v4.0 is coming soon</h3>
											<ul className="media-list underline m-b-15 p-b-15">
												<li className="media media-sm clearfix">
													<Link to="/email/inbox" className="pull-left">
														<img className="media-object rounded-corner" alt="" src="/assets/img/user/user-12.jpg" />
													</Link>
													<div className="media-body">
														<div className="email-from text-inverse f-s-14 f-w-600 m-b-3">
															from support@wrapbootstrap.com
														</div>
														<div className="m-b-3"><i className="fa fa-clock fa-fw"></i> Today, 8:30 AM</div>
														<div className="email-to">
															To: nguoksiong@live.co.uk
														</div>
													</div>
												</li>
											</ul>
											<ul className="attached-document clearfix">
												<li className="fa-file">
													<div className="document-file">
														<Link to="/email/detail">
															<i className="fa fa-file-pdf"></i>
														</Link>
													</div>
													<div className="document-name"><Link to="/email/detail">flight_ticket.pdf</Link></div>
												</li>
												<li className="fa-camera">
													<div className="document-file">
														<Link to="/email/detail">
															<img src="/assets/img/gallery/gallery-11.jpg" alt="" />
														</Link>
													</div>
													<div className="document-name"><Link to="/email/detail">front_end_mockup.jpg</Link></div>
												</li>
											</ul>

											<p className="f-s-12 text-inverse p-t-10"> 
												Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel auctor nisi, vel auctor orci. <br />
												Aenean in pretium odio, ut lacinia tellus. Nam sed sem ac enim porttitor vestibulum vitae at erat.
											</p>
											<p className="f-s-12 text-inverse">
												Curabitur auctor non orci a molestie. Nunc non justo quis orci viverra pretium id ut est. <br />
												Nullam vitae dolor id enim consequat fermentum. Ut vel nibh tellus. <br />
												Duis finibus ante et augue fringilla, vitae scelerisque tortor pretium. <br />
												Phasellus quis eros erat. Nam sed justo libero.
											</p>
											<p className="f-s-12 text-inverse">
												Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.<br /> 
												Sed tempus dapibus libero ac commodo.
											</p>
											<br />
											<br />
											<p className="f-s-12 text-inverse">
												Best Regards,<br />
												Sean.<br /><br />
												Information Technology Department,<br />
												Senior Front End Designer<br />
											</p>
										</div>
									</PerfectScrollbar>
								</div>
							</div>
						</div>
						<div className="wrapper text-right clearfix">
							<div className="btn-group">
								<Link to="/email/inbox" className="btn btn-white btn-sm disabled"><i className="fa fa-arrow-up"></i></Link>
								<Link to="/email/inbox" className="btn btn-white btn-sm"><i className="fa fa-arrow-down"></i></Link>
							</div>
							<div className="btn-group m-l-5">
								<Link to="/email/inbox" className="btn btn-white btn-sm"><i className="fa fa-times"></i></Link>
							</div>
						</div>
					</div>
				</div>
			</div>
		)
	}
}

export default EmailDetail;

// template/template_vuejs/src/pages/Email-detail.vue
<template>
	<!-- begin vertical-box -->
	<div class="vertical-box with-grid inbox">
		<!-- begin vertical-box-column -->
		<div class="vertical-box-column width-200 bg-light hidden-xs">
			<!-- begin vertical-box -->
			<div class="vertical-box">
				<!-- begin wrapper -->
				<div class="wrapper">
					<div class="d-flex align-items-center justify-content-center">
						<b-button v-b-toggle.emailNav variant="inverse" class="btn-sm mr-auto d-block d-lg-none">
							<i class="fa fa-cog"></i>
						</b-button>
						<router-link to="/email/compose" class="btn btn-inverse p-l-40 p-r-40 btn-sm">
							Compose
						</router-link>
					</div>
				</div>
				<!-- end wrapper -->
				<!-- begin vertical-box-row -->
				<b-collapse class="vertical-box-row collapse d-lg-table-row" id="emailNav">
					<!-- begin vertical-box-cell -->
					<div class="vertical-box-cell">
						<!-- begin vertical-box-inner-cell -->
						<div class="vertical-box-inner-cell">
							<!-- begin scrollbar -->
							<div data-scrollbar="true" data-height="100%">
								<!-- begin wrapper -->
								<div class="wrapper p-0">
									<div class="nav-title"><b>FOLDERS</b></div>
									<ul class="nav nav-inbox">
										<li class="active"><router-link to="/email/inbox"><i class="fa fa-inbox fa-fw m-r-5"></i> Inbox <span class="badge pull-right">52</span></router-link></li>
										<li><router-link to="/email/inbox"><i class="fa fa-flag fa-fw m-r-5"></i> Important</router-link></li>
										<li><router-link to="/email/inbox"><i class="fa fa-envelope fa-fw m-r-5"></i> Sent</router-link></li>
										<li><router-link to="/email/inbox"><i class="fa fa-pencil-alt fa-fw m-r-5"></i> Drafts</router-link></li>
										<li><router-link to="/email/inbox"><i class="fa fa-trash fa-fw m-r-5"></i> Trash</router-link></li>
									</ul>
									<div class="nav-title"><b>LABEL</b></div>
									<ul class="nav nav-inbox">
										<li><a href="javascript:;"><i class="fa fa-fw f-s-10 m-r-5 fa-circle text-inverse"></i> Admin</a></li>
										<li><a href="javascript:;"><i class="fa fa-fw f-s-10 m-r-5 fa-circle text-blue"></i> Designer & Employer</a></li>
										<li><a href="javascript:;"><i class="fa fa-fw f-s-10 m-r-5 fa-circle text-success"></i> Staff</a></li>
										<li><a href="javascript:;"><i class="fa fa-fw f-s-10 m-r-5 fa-circle text-warning"></i> Sponsorer</a></li>
										<li><a href="javascript:;"><i class="fa fa-fw f-s-10 m-r-5 fa-circle text-danger"></i> Client</a></li>
									</ul>
								</div>
								<!-- end wrapper -->
							</div>
							<!-- end scrollbar -->
						</div>
						<!-- end vertical-box-inner-cell -->
					</div>
					<!-- end vertical-box-cell -->
				</b-collapse>
				<!-- end vertical-box-row -->
			</div>
			<!-- end vertical-box -->
		</div>
		<!-- end vertical-box-column -->
		<!-- begin vertical-box-column -->
		<div class="vertical-box-column bg-light">
			<!-- begin vertical-box -->
			<div class="vertical-box">
				<!-- begin wrapper -->
				<div class="wrapper clearfix">
					<div class="pull-left">
						<div class="btn-group m-r-5">
							<a href="javascript:;" class="btn btn-white btn-sm"><i class="fa fa-reply m-r-3 m-r-xs-0"></i> <span class="hidden-xs">Reply</span></a>
						</div>
						<div class="btn-group m-r-5">
							<a href="javascript:;" class="btn btn-white btn-sm"><i class="fa fa-trash m-r-3 m-r-xs-0"></i> <span class="hidden-xs">Delete</span></a>
							<a href="javascript:;" class="btn btn-white btn-sm"><i class="fa fa-archive m-r-3 m-r-xs-0"></i> <span class="hidden-xs">Archive</span></a>
						</div>
					</div>
					<div class="pull-right">
						<div class="btn-group">
							<router-link to="/email/inbox" class="btn btn-white btn-sm disabled"><i class="fa fa-arrow-up"></i></router-link>
							<router-link to="/email/inbox" class="btn btn-white btn-sm"><i class="fa fa-arrow-down"></i></router-link>
						</div>
						<div class="btn-group m-l-5">
							<router-link to="/email/inbox" class="btn btn-white btn-sm"><i class="fa fa-times"></i></router-link>
						</div>
					</div>
				</div>
				<!-- end wrapper -->
				<!-- begin vertical-box-row -->
				<div class="vertical-box-row bg-white">
					<!-- begin vertical-box-cell -->
					<div class="vertical-box-cell">
						<!-- begin vertical-box-inner-cell -->
						<div class="vertical-box-inner-cell">
							<!-- begin scrollbar -->
							<vue-custom-scrollbar class="height-full">
								<!-- begin wrapper -->
								<div class="wrapper">
									<h3 class="m-t-0 m-b-15 f-w-500">Bootstrap v4.0 is coming soon</h3>
									<ul class="media-list underline m-b-15 p-b-15">
										<li class="media media-sm clearfix">
											<a href="javascript:;" class="pull-left">
												<img class="media-object rounded-corner" alt="" src="/assets/img/user/user-12.jpg" />
											</a>
											<div class="media-body">
												<div class="email-from text-inverse f-s-14 f-w-600 m-b-3">
													from support@wrapbootstrap.com
												</div>
												<div class="m-b-3"><i class="fa fa-clock fa-fw"></i> Today, 8:30 AM</div>
												<div class="email-to">
													To: nguoksiong@live.co.uk
												</div>
											</div>
										</li>
									</ul>
									<ul class="attached-document clearfix">
										<li class="fa-file">
											<div class="document-file">
												<a href="javascript:;">
													<i class="fa fa-file-pdf"></i>
												</a>
											</div>
											<div class="document-name"><a href="javascript:;">flight_ticket.pdf</a></div>
										</li>
										<li class="fa-camera">
											<div class="document-file">
												<a href="javascript:;">
													<img src="/assets/img/gallery/gallery-11.jpg" alt="" />
												</a>
											</div>
											<div class="document-name"><a href="javascript:;">front_end_mockup.jpg</a></div>
										</li>
									</ul>

									<p class="f-s-12 text-inverse p-t-10"> 
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel auctor nisi, vel auctor orci. <br />
										Aenean in pretium odio, ut lacinia tellus. Nam sed sem ac enim porttitor vestibulum vitae at erat.
									</p>
									<p class="f-s-12 text-inverse">
										Curabitur auctor non orci a molestie. Nunc non justo quis orci viverra pretium id ut est. <br />
										Nullam vitae dolor id enim consequat fermentum. Ut vel nibh tellus. <br />
										Duis finibus ante et augue fringilla, vitae scelerisque tortor pretium. <br />
										Phasellus quis eros erat. Nam sed justo libero.
									</p>
									<p class="f-s-12 text-inverse">
										Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.<br /> 
										Sed tempus dapibus libero ac commodo.
									</p>
									<br />
									<br />
									<p class="f-s-12 text-inverse">
										Best Regards,<br />
										Sean.<br /><br />
										Information Technology Department,<br />
										Senior Front End Designer<br />
									</p>
								</div>
								<!-- end wrapper -->
							</vue-custom-scrollbar>
							<!-- end scrollbar -->
						</div>
						<!-- end vertical-box-inner-cell -->
					</div>
					<!-- end vertical-box-cell -->
				</div>
				<!-- end vertical-box-row -->
				<!-- begin wrapper -->
				<div class="wrapper text-right clearfix">
					<div class="btn-group">
						<router-link to="/email/inbox" class="btn btn-white btn-sm disabled"><i class="fa fa-arrow-up"></i></router-link>
						<router-link to="/email/inbox" class="btn btn-white btn-sm"><i class="fa fa-arrow-down"></i></router-link>
					</div>
					<div class="btn-group m-l-5">
						<router-link to="/email/inbox" class="btn btn-white btn-sm"><i class="fa fa-times"></i></router-link>
					</div>
				</div>
				<!-- end wrapper -->
			</div>
			<!-- end vertical-box -->
		</div>
		<!-- end vertical-box-column -->
	</div>
	<!-- end vertical-box -->
</template>

<script>
import PageOptions from '../config/PageOptions.vue'

export default {
	data() {
		PageOptions.pageContentFullWidth = true;
		PageOptions.pageContentFullHeight = true;

		return { }
	},
	beforeRouteLeave (to, from, next) {
		PageOptions.pageContentFullWidth = false;
		PageOptions.pageContentFullHeight = false;
		next();
	}
}
</script>
