// template/template_react_startup/src/pages/Home.js
import React from 'react';
import { Link } from 'react-router-dom';
import { Panel, PanelHeader, PanelBody } from './../components/panel/panel.jsx';

class Home extends React.Component {
	render() {
		return (
			<div>
				<ol className="breadcrumb float-xl-right">
					<li className="breadcrumb-item"><Link to="/">Home</Link></li>
					<li className="breadcrumb-item active">Active Page</li>
				</ol>
				<h1 className="page-header">Home <small>header small text goes here...</small></h1>
				<Panel>
					<PanelHeader>Panel Title here</PanelHeader>
					<PanelBody>
						Panel Content Here
					</PanelBody>
				</Panel>
			</div>
		)
	}
}

export default Home;

// template/template_vuejs_startup/src/pages/Home.vue
<template>
	<div>
		<!-- begin breadcrumb -->
		<ol class="breadcrumb float-xl-right">
			<li class="breadcrumb-item active"><a href="javascript:;">Home</a></li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">Home <small>header small text goes here...</small></h1>
		<!-- end page-header -->
		<panel title="Panel title here">
			<p>
				Panel content here
			</p>
		</panel>
	</div>
</template>
